### ISSUE TITLE
Set up gulp

### ISSUE THREAD

**Issue by Smona** [Smona/thepoliticalrev.org#12]
* gulp-pleeease
* gulp-uncss
* gulp-imagemin
* gulp-uglifyjs
* webpack-stream

**Comment by leggomuhgreggo** [comment]
I like gulp, but I feel like it might overlap webpack. Webpack, delicate flower of a build tool though it is, can flex all those functions. Gulp may be easier to reason about though; don't mean to add to tech choice paralysis. I can whip a script for either option this weekend, if you'd like to delegate.

**Comment by Smona** [comment]
I've actually been enjoying webpack quite a bit. But the way i understand it you can only process assets that are required by your module. Can webpack monitor css changes and run postcss or similar? And can it optimize images?

**Comment by leggomuhgreggo** [comment]
Yeah man Webpack is super versatile. It'll pretty much do your taxes and fold your laundry if you ask nicely. Definitely wouldn't want to slow anyone's roll, but here're some details on how it could work with webpack: 

If we elect to not include style dependencies in each component, I think you can just have a second  entry point for something like `index.scss` *and use the proper css loaders.

https://github.com/byteclubfr/pleeease-loader
https://github.com/PurifyCSS/purifycss-webpack-plugin (~uncss. Alternatively we could use css modules)
https://github.com/tcoopman/image-webpack-loader (although we might do better to just set up a free cloudinary account)

I think Webpack will auto uglify in production mode.

Edit: *Added little clarification about CSS process

**Comment by iancullinane** [comment]
I am personally against `gulp` and `grunt`.  I feel like they greatly confuse the build process unnecessarily. Webpack is great keep on keeping on, but I don't see the value in `gulp` or `grunt` as a build tool. They don't give you anything that `Make` and the command-line can't already do more elegantly, with less code, and fewer dependencies.

**Comment by leggomuhgreggo** [comment]
I pretty much agree with that. The WP theme we're adapting to rn, has a built in gulp build, but it doesn't strike me as being a matter that calls for any action. Ain't broke, yada yada Webpack sounds good to me down the road, though, especially if our builds call for higher complexity features Webpack is better suited to.

**Comment by austinheap** [comment]
One thing to call out is the WP boilerplate we're trying out -- [Sage](https://github.com/roots/sage) -- is currently using gulp for their stable release ([v8.5](https://github.com/roots/sage/blob/223fc4811b960c1f49643a5ddb282a78fb5e5086/README.md)). They are moving to Webpack for [v9](https://github.com/roots/sage/blob/master/README.md) and obviously we'd like to have an upgrade path. Just food for thought!

Edit: We could also bite the bullet and go straight for Sage v9 (and Webpack) even though it's not stable nor release candidate yet. That just means we'll be inheriting their problems though so... might not be the best use of time from an opportunity cost perspective.

**Comment by Smona** [comment]
We'll use the gulp setup included with sage, and consider customizing the webpack build when we upgrade. No need to submit new issues to this repo as it's just holding the code we need to import into the new site
