### ISSUE TITLE
Create test staging area for website instead of pushing live changes

### ISSUE THREAD

**Issue by tngreene** [Smona/thepoliticalrev.org#22]
Hi guys,
Idk what's going on, but over time as I've seen the website develop, it seems like changes get made to the live public website. Currently the take action page is filled with Wordpress short codes instead of actual content.

It looks unprofessional and there's probably some security thing or other or something. Best practices and such.

We should definitely be making sure that the only thing that's live to the public if they visit our site is a good looking (hopefully non-buggy) site.

**Comment by tngreene** [comment]
gah I'm so stupid and didn't read the readme. How do I close this myself!

**Comment by Smona** [comment]
That's on the wordpress site, right? While I agree it's unprofessional to have out there, that link has not been published. Also, this is the repo for the "old site" ♥️
